debian/rules

It avoids a warning in configuring

Remove no longer pymapi to disable

---

debian/openchangeserver.install

This will be needed when openchange_group reaches this branch.

Add openchange_group to openchangeserver.install

---

Makefile
mapiproxy/libmapistore/backends/indexing_mysql.c
mapiproxy/libmapistore/mapistore.h
mapiproxy/libmapistore/mapistore_notification.c
mapiproxy/services/plugins/dovecot/openchange-plugin.c
mapiproxy/util/oc_memcached.c
mapiproxy/util/oc_memcached.h

Reuse memcached connections based on configuration string, this normally means that we will have two open connections against memcached: one for indexing and another for notifications and those connections will be reused by all sessions and operations.

 Reuse memcached connections

---

exchange.idl
libmapi/FXICS.c
libmapi/libmapi.h
mapiproxy/servers/default/emsmdb/oxcfxics.c
ndr_mapi.c
utils/mapitest/module.c
utils/mapitest/modules/module_oxcfxics.c

Several improvements over that rop:
* Read from NDR the SyncReadStateChanges payload
* Easier to read and maintain SyncReadStateChanges server ROP
* Read from the NDR dump the messages whose read flag is changed
* Mimetise Online mode for SetReadFlag on offline mode
* Adding checks on returned values
* Implement SyncReadStateChanges mapitest which required client side call in libmapi.

Improvements over SyncImportReadStateChanges OXCFXICS ROP

---

mapiproxy/servers/default/emsmdb/oxcfxics.c

On procedures where the returned value is checked.
There are places where the check has not been added because the returned value is not checked and I think this work was already started.

oxcfxics: Checks on openchangedb_get_MailboxReplica

---

CHANGES.md
mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.c
mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.h
mapiproxy/servers/default/emsmdb/emsmdbp.c
mapiproxy/services/plugins/dovecot/ChangeLog
mapiproxy/services/plugins/dovecot/README.md
mapiproxy/services/plugins/dovecot/openchange-plugin.c

* Use email (obtained from `proxyAddresses:SMTP:xxxx` entry which must be always present for openchange users) to create notification session.
* Removed `openchange_cn` option from dovecot plugin, always using email.
This fixes scenarios where the username is different from the email, for example username `bob` with an email `bobby@domain.com`.

Notifications when username is different from email

---

mapiproxy/libmapistore/mapistore_interface.c

Set the log level of a configuration error which makes
mapistore initialization fail to the same log level than
other fatal mapistore initialization errors.

mapistore: all init error has the same log level

---

mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.c
mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.c

session could not be found there so we must use r->in.handle->uuid instead

Avoid crash because using session->uid

---

CHANGES.md
mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c

Tevent loop is in charge of freeing session private_data
RD-5 # resolve # time 4h

Fix double free crash on asyncemsmdb sessions

---

CHANGES.md
script/openchange_user_cleanup.py

SQL identifiers were not correctly escaped so the sentences could
fail in some cases. For example, users with hyphens, like 'user-a'.
If we want CHANGES.md: Fixed openchange_user_cleanup.py bug which some user names with non alphanumerics characters.

openchange_user_cleanup.py: Fixed SQL identifer escapes

---

config.mk.in
mapiproxy/libmapiproxy/backends/openchangedb_mysql.c

After migration framework implemented, OPENCHANGEDB_DATA_DIR is not
longer needed.

ocdb-mysql: Remove compilation warning

---

mapiproxy/services/plugins/dovecot/README.md
mapiproxy/services/plugins/dovecot/openchange-plugin.c

In this type of socket, the nn_connect may not fail but the nn_send
and we have to clarify these situations with the proper error message.

dovecot-plugin: Clarify misleading err msg on send failure

---

CHANGES.md
libmapi/FXICS.c
libmapi/libmapi.h
mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.h
mapiproxy/servers/default/emsmdb/emsmdbp_object.c
mapiproxy/servers/default/emsmdb/oxcfxics.c
utils/mapitest/module.c
utils/mapitest/modules/module_oxcfxics.c

* Implement SyncImportDeletes operation in client side
* Along with mapitest to test it
* Folder deletion on cached mode now works
* It was only working if the folder was at INBOX's level
* Added additional checks on SyncImportDeletes

 Improvements over SyncImportDeletes OXCFXICS ROP

---

CHANGES.md
ndr_fasttransfer.c

Likewise PT_UNICODE, we use the same decoding.
Example from a contact message in a messageChange element:
PidTagContactEmailAddresses: struct mapi_SLPSTRArrayW
cValues                  : 0x00000001 (1)
strings: ARRAY(1)
strings: struct mapi_LPWSTR
lppszW                   : 'email@example.com'

fxbuffer: Decode PT_MV_UNICODE

---

CHANGES.md
libmapi/idset.c
testsuite/libmapi/mapi_idset.c

Treating non-single two element rawidset likewise bigger idsets.
A rawidset with two globcnt were treated as single one with apparently no reason for this.
We have removed that special case and create unit tests for testing `RAWIDSET_convert_to_idset` function.
This was causing returning a bad MetaIdsetGiven when syncing the transfer state after performing operations where more than one message were involved and those messages were non-consecutive ones.

Fix conversion non-single rawidset with two elements

---

CHANGES.md
libmapi/idset.c
mapiproxy/servers/default/emsmdb/oxcfxics.c
utils/mapitest/modules/module_oxcfxics.c

Fixing two possible source of sync issues after performing upload operations:
* Do not return invalid GLOBSET range of identifiers if the first operation of a folder (no data in client) is an upload.
* Returning only affected change numbers after uploading changes that involves several messages
I've also extended mapitest to assure my assumptions and verify the code. That has encouraged finding more bugs :).

Improving idset management on upload operations

---

libmapi/oc_log.h

With this change, the log level set in samba configuration is honored in OC_DEBUG wrapper. Before this patch, if a developer sets the log level to 5, it requires a level 6 in samba configuration to be logged.
I think this should be rollbacked once OpenChange uses its own debugging system.

Fix log level on OC_DEBUG wrapper

---

CHANGES.md
libmapi/idset.c
testsuite/libmapi/mapi_idset.c

There are times where the IDSET is big enough that the MAPI client is splitting upload of the state property into several `SyncUploadStreamStateContinue` requests making crash the server if the `dcerpc_mapiproxy:ndrdump = true` option is set to true.

Avoid aborting on IDSET parsing

---

CHANGES.md
mapiproxy/servers/default/emsmdb/oxcfxics.c

A bug in mapistore layer could make message table impossible to open.
It is not expected to abort here but to return an error.

oxcfxics: Do not abort on failing open msg table in SyncConfigure

---

CHANGES.md
libmapi/idset.c
testsuite/libmapi/mapi_idset.c

Two bugs were spotted:
* The *StartingValue* was set to a wrong value because the buffer_position
was altered before stored additional data that is combined in memory
* The GLOBSET ranges were incorrectly set because the calculated
value was based on the bit value, which checks the mask against, instead
of the position in the loop.
Two unit tests were added that cover the 100% of the
`GLOBSET_parser_do_bitmask` code.
The consequence of this bug is described as follows:
Once an idset is incorrectly decoded for one of the fxics meta-properties,
when they are returned as the final result of an upload/download operation
in the FastTransfer Buffer, it returns an inconsistent idset with incorrect
GLOBSET ranges. For instance, having a folder whose identifiers the client
does not have leads to …

libmapi: Decoding GLOBSETs properly which have bitmask command

---

CHANGES.md
libmapi/idset.c
testsuite/libmapi/mapi_idset.c

On downloading changes we are merging now into one GLOBSET range,
ranges that are consecutive when merging idsets.
See the following example for details:
[0x8c2c03000000:0xeb2204000000]
[0x5c2304000000:0x622304000000]
Merge with:
[0x632304000000:0x632304000000]
It will produce the following idset:
[0x8c2c03000000:0xeb2204000000]
[0x5c2304000000:0x632304000000]
Added unit tests to `IDSET_merge_idsets` to avoid regressions that cover function `IDSET_compact_ranges`.

libmapi: Optimise idset data usage with consecutive ranges

---

CHANGES.md
mapiproxy/servers/default/emsmdb/oxcfxics.c

This is a regression introduced by 4ede2afd.
This makes OXCFXICS testsuite pass again.

Do not fail receiving an empty idset on SyncUploadStateStreamEnd

---

CHANGES.md
utils/mapiprofile.c

It took me a gdb session to realise that...

Notify missing --profile when using --create in mapiprofile

---

script/bug-analysis/patches/packaging_impl.py

In patch to retrace.
It is intended to fix old crashes to be able to retrace them.

Added missing packages binaries from samba source

---

CHANGES.md
Makefile
mapiproxy/libmapiproxy/libmapiproxy.h
mapiproxy/libmapistore/mapistore_interface.c
mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c
mapiproxy/servers/default/emsmdb/emsmdbp.c
mapiproxy/servers/default/emsmdb/emsmdbp_object.c
mapiproxy/servers/default/emsmdb/oxcmsg.c
mapiproxy/servers/default/emsmdb/oxcstor.c
mapiproxy/servers/default/emsmdb/oxomsg.c
mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.c
mapiproxy/servers/default/nspi/emsabp.c
mapiproxy/util/samdb.c
mapiproxy/util/samdb.h

Samba 4.3 introduced a new behavior, ldap reconnection is not working in
ldb.
A reconnect procedure is added to avoid errors when LDAP connection
is lost. `SAFE_LDB_SEARCH` macro takes charge of checking results and
trying to reconnect on error.
This may be a temporary workaround while we work on samba upstream

Reconnect LDAP pipes if broken

---

mapiproxy/libmapistore/mapistore_backend.c

Log a message if the backend store path cannot be opened. If the default
backend path is used, and it does not exist, you currently only get the
messages:
(mapistore_backend_init): No mapistore backends available (using backend path '(null)'
(mapistore_init): mapistore_backend_init: Storage backend initialization failed
(emsmdbp_init): MAPISTORE initialization failed
It seems helpful to log exactly what goes wrong.

Log failure opening the backend store path

---

CHANGES.md
libmapi/IABContainer.c
libmapi/libmapi.h
libmapi/nspi.c
mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.c
utils/mapitest/modules/module_nspi.c

Write a mapitest to make sure it is working.
The bug comes from a bug in an Outlook client request which derives from a bug in Contacts from OpenChange server side... :dango:

NSPI: Manage NULL as query values in ResolveNames ROPs

---

mapiproxy/libmapistore/backends/namedprops_mysql.c

If the `named_properties` table is empty, the query
SELECT max(mappedId) FROM <table>
returns `NULL`, causing a crash in `strtol()` later. Checking if `row[0]` is not `NULL` makes the code return `MAPISTORE_ERR_DATABASE_OPS` instead of crashing.

Fix crash caused by empty named_properties table

---

CHANGES.md
python/openchange/web/auth/NTLMAuthHandler.py

'Bearer' is sent in HTTP_AUTHORIZATION to start the OAuth2 process.
The exception was:
```
File "/usr/lib/python2.7/dist-packages/ocsmanager/config/middleware.py", line 77, in ntlm_env_setter
return auth_handler(environ, start_response)
File "/usr/lib/python2.7/dist-packages/openchange/web/auth/NTLMAuthHandler.py", line 583, in __call__
ntlm_payload = auth[5:].decode("base64")
File "/usr/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
output = base64.decodestring(input)
File "/usr/lib/python2.7/base64.py", line 321, in decodestring
return binascii.a2b_base64(s)
Error: Incorrect padding
```

ntlm: Do not crash if we receive OAuth2 request

---

mapiproxy/libmapiproxy/backends/openchangedb_logger.c
testsuite/libmapiproxy/openchangedb_logger.c

To ease debugging problems with zeroes in ChangeKey property.
Affected functions are: get_MailboxReplica and get_MailboxGuid

ocdb-logger: Dump Replica GUID on related functions

---

CHANGES.md
mapiproxy/servers/default/emsmdb/oxcfxics.c

Using the given `CNSet_Seen` meta-property sent by the client we can ask
to the mapistore layer to retrieve only the missing messages.
We assume, likewise it was previously, the elements up to the first
globset range are not required as this element is the first CN seen by the client
upon first sync with empty state.

oxcfxics: Perform CN restrictions on downloading changes to client

---

CHANGES.md
mapiproxy/libmapistore/mapistore_interface.c
mapiproxy/servers/default/emsmdb/oxomsg.c

* Notify when mapistore fails to deliver by sending back MAPI_E_NETWORK_ERROR
* This requires https://github.com/zentyal/sogo/pull/226 to work
* Stop SMTP server to test it
* Uniform TransportSend and SubmitMessage ROPs
* This makes missing sharing feature on SubmitMessage (used by Outlook Online mode) available

Fixes on submitting email messages

---

libmapi/property.c
testsuite/libmapi/mapi_property.c

The parsers of several structures were freeing their array fields
because they were hanging from the `ndr_pull` structure used to parse
the structure.

Hang talloc arrays inside structs from the main mem_ctx

---

CHANGES.md
mapiproxy/servers/default/emsmdb/emsmdbp_provisioning.c

This is a band-aid until we have synchronisation in oxcfxics for
deleted folders and notifying the client for that.

oxcstor: Deny the removal of special folders on provisioning

---

CHANGES.md
mapiproxy/servers/default/emsmdb/oxcfxics.c

In order to notify back the client in the resulting idsets and
removing from indexing entries, if not already done.

oxcfxics: Importing already deleted deletions as success

---

property.idl

The PidLidMeetingType property ([MS-OXOCAL] 2.2.6.5) indicates the type
of the meeting request or update object.

oxocal: Add PidLidMeetingType possible values

---

CHANGES.md
exchange.idl
ndr_fasttransfer.c

For example:
0x91BC1003 (LID 0x00008028): struct LongArray_r
cValues                  : 0x00000000 (0)
lpl                      : *
lpl: ARRAY(0)

fxdump: Dump PT_MV_LONG properties in FastTransfer Buffer NDR

---

CHANGES.md
mapiproxy/libmapistore/backends/indexing_mysql.c
script/openchange_user_cleanup.py

Stores when an user has been initialized, so the warm up process will be done only once.
Additional changes done:
* Indexing keys are now prefixed with username
* `openchange_user_cleanup` now works properly with memcached on different place than localhost (checks samba config to get memcached host)

Optimize indexing warm up

---

mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c
mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.h

Instead of using event context as parent of asyncemsdb sessions now we will use our own memory context and release it with the `mpm_session` (so control it ourselves instead of relaying external contexts)
This fixes, at least, three known bugs:
- Crash when stopping samba when trying to print a released `char *`. This happened when shutting down samba and only when the memory was not printable (no `\0`)
- Fail to restart samba because failing to liberate session cause samba to shutdown slowler than usual and new samba process could not start properly because of that (`service samba-ad-dc restart` didn't work, but manually stop + start did).
- Not releasing/updating resolver entries on memcached so everytime we restarted samba, we were increasing and increasing the number of resolvers (to …

Change asyncemsmdb_session ownership

---

CHANGES.md
mapiproxy/services/ocsmanager/development.ini
mapiproxy/services/ocsmanager/ocsmanager.ini
mapiproxy/services/ocsmanager/ocsmanager/config/environment.py
mapiproxy/services/ocsmanager/ocsmanager/lib/config.py

The retries occur until it connects but they could be limited
in the INI file.
The backoff time between attempts increases on each attempt, from 5 seconds
to a maximum of 60.

Retry the samba connection attempt on ocsmanager startup

---

libmapi/idset.c
testsuite/libmapi/mapi_idset.c

`RAWIDSET_find_by_ID` can return NULL without initialising
`last_glob_idset` when the rawidset isn't ID-based. Therefore, if we
pass an ID-based idset to this function it will try to access the `next`
attribute of a NULL pointer, causing a segmentation fault.

Avoid crash in RAWIDSET_push_eid

---

mapiproxy/servers/default/emsmdb/oxosfld.c

Both `PersistData` and `PersistElement` could had `PERSIST_SENTINEL` value that indicates they are the last valid value on the array (even if the array has more elements).

oxosfld: stop on PERSIST_SENTINEL

---

mapiproxy/libmapiproxy/backends/openchangedb_mysql.c
mapiproxy/libmapiserver/libmapiserver.h
mapiproxy/libmapiserver/libmapiserver_oxcdata.c
mapiproxy/libmapiserver/libmapiserver_oxcprpt.c
mapiproxy/libmapistore/mapistore_namedprops.c
mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c
mapiproxy/servers/default/emsmdb/emsmdbp_object.c
mapiproxy/servers/default/emsmdb/oxcfxics.c
mapiproxy/servers/default/emsmdb/oxcmsg.c
mapiproxy/servers/default/emsmdb/oxcprpt.c
mapiproxy/servers/default/emsmdb/oxctabl.c

Mostly refactorization. It only removes some `abort()` and now we will return error on those scenarios.

Do not abort unsupported property type

---

mapiproxy/servers/default/emsmdb/oxcfold.c
mapiproxy/servers/default/emsmdb/oxcfxics.c
mapiproxy/servers/default/emsmdb/oxcmsg.c
mapiproxy/servers/default/emsmdb/oxcnotif.c
mapiproxy/servers/default/emsmdb/oxcperm.c
mapiproxy/servers/default/emsmdb/oxcprpt.c
mapiproxy/servers/default/emsmdb/oxcstor.c
mapiproxy/servers/default/emsmdb/oxctabl.c
mapiproxy/servers/default/emsmdb/oxorule.c

In order to avoid sync issues messages when an opening resource failed:
[80040108-501-80040108-1340]
According to [MS-OXCDATA] 2.4.1, the ecNullObject marks that an object handle
reference in the RPC buffer could not be resolved.

emsmdb: Replace MAPI_E_INVALID_OBJECT to ecNullObject

---

mapiproxy/servers/default/emsmdb/oxosfld.c

Although the final result is equal to 0x0.
mapiproxy/servers/default/emsmdb/oxosfld.c: In function ‘oxosfld_is_special_folder’:
mapiproxy/servers/default/emsmdb/oxosfld.c:181:71: warning: comparison between ‘enum ElementID’ and ‘enum PersistID’ [-Wenum-compare]
if (persist_element.ElementID == PERSIST_SENTINEL) {

oxosfld: Fix compilation warning

---

CHANGES.md
Makefile
mapiproxy/libmapiproxy/libmapiproxy.h
mapiproxy/libmapiproxy/mapi_logon.c
mapiproxy/libmapistore/mapistore_backend.c
mapiproxy/libmapistore/mapistore_interface.c
mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.c
mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.h
mapiproxy/servers/default/emsmdb/emsmdbp.c
mapiproxy/servers/default/emsmdb/emsmdbp_object.c
mapiproxy/servers/default/emsmdb/emsmdbp_provisioning.c
mapiproxy/servers/default/emsmdb/oxcfold.c
mapiproxy/servers/default/emsmdb/oxcfxics.c
mapiproxy/servers/default/emsmdb/oxcmsg.c
mapiproxy/servers/default/emsmdb/oxcnotif.c
mapiproxy/servers/default/emsmdb/oxcperm.c
mapiproxy/servers/default/emsmdb/oxcprpt.c
mapiproxy/servers/default/emsmdb/oxcstor.c
mapiproxy/servers/default/emsmdb/oxctabl.c
mapiproxy/servers/default/emsmdb/oxomsg.c
mapiproxy/servers/default/emsmdb/oxorule.c
mapiproxy/servers/default/emsmdb/oxosfld.c
mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.c
mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.h
mapiproxy/servers/default/nspi/emsabp.c
mapiproxy/servers/default/nspi/emsabp_property.c
testsuite/libmapiproxy/logon_table.c
testsuite/testsuite.c
testsuite/testsuite.h

Give support to distinguish between the logged user (the one provided in **Logon ROP**) and the authenticated user (the one authenticated in **EcDoConnectEx** and **EcDoConnect**) and store the logon table as explained in [MS-OXCROPS] 3.1.4.2 ADM.
It requires https://github.com/zentyal/sogo/pull/250 to work.

Sharing support
